#!/usr/bin/env python
"""Run a few representative messages through the agent and dump the trace to
docs/demo_transcript.md, so the pipeline is visible without an interactive run.

  make demo-run     # regenerate the transcript
  make demo         # interactive: type your own messages
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from trustagent.agent import TrustAgent
from trustagent.config import load_config
from trustagent.intents import LLMClassifier
from trustagent.retrieval import Retriever

EXAMPLES = [
    "my downloaded songs won't play offline on the train, so annoying",
    "you charged me twice for premium this month, I want one refunded",
    "hello I think my account has been hacked, someone is playing music from another country",
    "can you please add Pharoahe Monch - Internal Affairs to spotify?",
    "sleep timer when? I don't want music running all night",
]


def main():
    cfg = load_config()
    retr = Retriever.load(cfg.path("artifacts") / "retriever")
    agent = TrustAgent(cfg, retr, LLMClassifier(cfg))

    out = ["# Demo transcript",
           "",
           f"Generated by `make demo-run`. Brand: **{cfg.brand}**. "
           f"Agent model: `{cfg.model('agent')['model']}`.",
           "",
           "Each block is one incoming message run through classify -> retrieve -> "
           "draft -> decide. For a live version type your own messages with `make demo`.",
           ""]
    for msg in EXAMPLES:
        r = agent.handle(msg)
        out += [
            "---", "",
            f"**Customer:** {msg}", "",
            f"- intent: `{r['intent']}` (confidence {r['intent_confidence']:.2f}, "
            f"risk {r['risk_tier']})",
            f"- precedent support: {r['retrieval_support']:.2f}"
            + (f"  ·  top match: _{r['evidence'][0]['past_customer'][:80]}_" if r['evidence'] else ""),
            f"- draft: {r['draft_reply']}",
            f"- **decision: {r['action'].upper()}** — {r['reason']}",
            "",
        ]
    dst = Path("docs/demo_transcript.md")
    dst.parent.mkdir(exist_ok=True)
    dst.write_text("\n".join(out))
    print("wrote", dst)


if __name__ == "__main__":
    main()
